/**
 * Teaching Pack PPTX Generator
 * Requirements:
 *   npm i pptxgenjs
 * Run:
 *   node generate_slides.js
 * Output:
 *   ./out/Mechatronics_Teaching_Pack.pptx
 */
const pptxgen = require("pptxgenjs");
const fs = require("fs");
const path = require("path");

const OUT_DIR = "out";
if (!fs.existsSync(OUT_DIR)) fs.mkdirSync(OUT_DIR);

function addTitleSlide(pptx) {
  const slide = pptx.addSlide();
  slide.background = { color: "0B1F3B" };
  slide.addText("Mechatronics Engineering (B.Eng.)", {
    x: 0.6, y: 1.5, w: 12.2, h: 0.8,
    fontFace: "Calibri", fontSize: 40, color: "FFFFFF", bold: true
  });
  slide.addText("Teaching Pack — Program Overview, Assessment Model, Semester Snapshots", {
    x: 0.6, y: 2.4, w: 12.2, h: 0.6,
    fontFace: "Calibri", fontSize: 18, color: "DCE6F2"
  });
  slide.addText("Generated deck (editable)", {
    x: 0.6, y: 6.8, w: 12.2, h: 0.4,
    fontFace: "Calibri", fontSize: 12, color: "DCE6F2"
  });
}

function addAgenda(pptx) {
  const slide = pptx.addSlide();
  slide.addText("Agenda", { x: 0.7, y: 0.4, w: 12, h: 0.6, fontFace: "Calibri", fontSize: 32, bold: true, color: "1F4E79" });
  const bullets = [
    "Program pillars & learning outcomes",
    "Kits, lab infrastructure & safety",
    "Assessment model & rubrics",
    "Semester-by-semester snapshots (1–8)",
    "Capstone expectations & portfolio outputs"
  ];
  slide.addText(bullets.map(b => `• ${b}`).join("\n"), { x: 0.9, y: 1.4, w: 12, h: 5, fontFace: "Calibri", fontSize: 20, color: "333333" });
}

function addPillars(pptx) {
  const slide = pptx.addSlide();
  slide.addText("Program Pillars", { x: 0.7, y: 0.4, w: 12, h: 0.6, fontSize: 30, bold: true, color: "1F4E79" });
  const pillars = [
    "Mechanical systems & design",
    "Electronics & embedded systems",
    "Control systems & robotics",
    "Software, data & automation",
    "Systems integration & professional practice"
  ];
  slide.addText(pillars.map(p => `• ${p}`).join("\n"), { x: 0.9, y: 1.3, w: 12, h: 5.5, fontSize: 20, color: "333333" });
}

function addKitSlide(pptx) {
  const slide = pptx.addSlide();
  slide.addText("Core Student Kit", { x: 0.7, y: 0.4, w: 12, h: 0.6, fontSize: 30, bold: true, color: "1F4E79" });
  const bullets = [
    "Arduino Uno/Nano + ESP32 dev board",
    "Raspberry Pi (3/4/5) + camera",
    "Sensors: temp/humidity, ultrasonic, IMU, light, encoders",
    "Actuators: servos, DC motors + driver, stepper + driver",
    "Multimeter + soldering tools + basic hand tools",
    "Optional: 3D printing access, calipers, fastener kit"
  ];
  slide.addText(bullets.map(b => `• ${b}`).join("\n"), { x: 0.9, y: 1.3, w: 12, h: 5.8, fontSize: 18, color: "333333" });
}

function addAssessment(pptx) {
  const slide = pptx.addSlide();
  slide.addText("Assessment Model (Hands-on Courses)", { x: 0.7, y: 0.4, w: 12.5, h: 0.6, fontSize: 28, bold: true, color: "1F4E79" });
  const bullets = [
    "Labs + checkouts: 25–35%",
    "Lab notebook + documentation: 15–25%",
    "Practical exams: 15–25%",
    "Projects: 25–40%",
    "",
    "Project rubric: Functionality 30%, Engineering quality 20%, Software quality 20%, Documentation 15%, Design reasoning 15%"
  ];
  slide.addText(bullets.map(b => (b ? `• ${b}` : "")).join("\n"), { x: 0.9, y: 1.2, w: 12.5, h: 6, fontSize: 18, color: "333333" });
}

function addSemesterSnapshot(pptx, n, focus, builds) {
  const slide = pptx.addSlide();
  slide.addText(`Semester ${n} Snapshot`, { x: 0.7, y: 0.4, w: 12.5, h: 0.6, fontSize: 30, bold: true, color: "1F4E79" });
  slide.addText(`Focus: ${focus}`, { x: 0.9, y: 1.2, w: 12.5, h: 0.4, fontSize: 16, color: "333333", italic: true });
  slide.addText(builds.map(b => `• ${b}`).join("\n"), { x: 0.9, y: 1.8, w: 12.5, h: 5.4, fontSize: 18, color: "333333" });
}

function addCapstone(pptx) {
  const slide = pptx.addSlide();
  slide.addText("Capstone (Year 4) — What ‘Good’ Looks Like", { x: 0.7, y: 0.4, w: 12.7, h: 0.6, fontSize: 26, bold: true, color: "1F4E79" });
  const bullets = [
    "Clear requirements + acceptance tests (traceable)",
    "CAD + drawings + assembly plan",
    "Electrical schematic + wiring harness diagram",
    "Firmware architecture + fault handling + logs",
    "Validation report with evidence (plots, checklists, test logs)",
    "Costed BOM + procurement plan",
    "Safety/risk notes + mitigations (FMEA-lite)"
  ];
  slide.addText(bullets.map(b => `• ${b}`).join("\n"), { x: 0.9, y: 1.2, w: 12.7, h: 6.2, fontSize: 18, color: "333333" });
}

function main() {
  const pptx = new pptxgen();
  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "Generated by ChatGPT";

  addTitleSlide(pptx);
  addAgenda(pptx);
  addPillars(pptx);
  addKitSlide(pptx);
  addAssessment(pptx);

  addSemesterSnapshot(pptx, 1, "Measurement + sensors + documentation", [
    "MEC110: calibration, filtering, logging",
    "Portfolio: sensor calibration notebook + smart desk monitor"
  ]);
  addSemesterSnapshot(pptx, 2, "Actuators + mechanisms + safe power", [
    "MEC120: DC/servo/stepper + homing + motion profiles",
    "Portfolio: linear stage/conveyor + wiring safety build"
  ]);
  addSemesterSnapshot(pptx, 3, "Embedded robustness + instrumentation", [
    "EMB210: interrupts, comms, watchdogs, telemetry",
    "Portfolio: wireless condition monitor + reusable driver pack"
  ]);
  addSemesterSnapshot(pptx, 4, "Control foundations + integration", [
    "CON240 + MEC250: identify system + tune PID with logs",
    "Portfolio: PID speed controller + bring-up guide"
  ]);
  addSemesterSnapshot(pptx, 5, "Robotics integration (Pi + MCU)", [
    "ROB315: odometry + IMU fusion + camera pipeline",
    "Portfolio: rover v1 + vision demo"
  ]);
  addSemesterSnapshot(pptx, 6, "Automation + vision + fault handling", [
    "AUT365: sorting cell with jam detection and logs",
    "Portfolio: vision sorter + safety/FMEA case study"
  ]);
  addSemesterSnapshot(pptx, 7, "Capstone planning + prototype", [
    "CAP401: PDR/CDR + prototype subsystem + test plan",
    "Portfolio: proposal package + prototype evidence"
  ]);
  addSemesterSnapshot(pptx, 8, "Capstone delivery + validation", [
    "CAP402: full build + verification matrix + final demo",
    "Portfolio: final product + engineering retrospective"
  ]);

  addCapstone(pptx);

  const outPath = path.join(OUT_DIR, "Mechatronics_Teaching_Pack.pptx");
  pptx.writeFile({ fileName: outPath }).then(() => {
    console.log("Wrote", outPath);
  }).catch((e) => {
    console.error(e);
    process.exit(1);
  });
}

main();
